name             'newrelic_test'
maintainer       'Kirill Kouznetsov'
maintainer_email 'agon.smith@gmail.com'
license          'Apache 2.0'
description      'Some tests for newrelic cookbook.'
long_description 'Some tests for newrelic cookbook.'
version          '0.1.0'

depends 'ruby_build'
depends 'ruby_rbenv'
depends 'newrelic'
